### ISSUE TITLE
`ErrorInfo` detail field is object in registry responses

### ISSUE THREAD

**Issue by petkovicdanilo** [containers/oci-spec-rs#59]
Although [spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes) says that `detail` field in `ErrorInfo` is string with unstructured data it seems that all registries make `detail` field an object.

For example, Dockerhub returns this for unknown manifest:
```json
{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "message": "manifest unknown",
            "detail": {
                "Tag": "lates"
            }
        }
    ]
}
```

Quay:
```json
{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "detail": {},
            "message": "manifest unknown"
        }
    ]
}
```

Microsoft's MCR :
```json
{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "message": "manifest tagged by \"lates\" is not found",
            "detail": {
                "Tag": "lates"
            }
        }
    ]
}
```

This results in failure to deserialize any of the above `ErrorResponse` structs.

Is this the problem of registry implementers, this library or the spec itself?

**Comment by Furisto** [comment]
Considering that the exact wording of the spec is 

> The detail field is OPTIONAL and MAY contain **arbitrary JSON** data providing information the client can use to resolve the issue 

the most correct (but not the most convenient) way would be to expose a Json type like this:

```
pub enum Json {
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Array(Vec<Json>),
    Object(Map<String, Json>),
}
```
and then you have to match to know what you got. Serde already defines such a [value](https://docs.serde.rs/serde_json/value/enum.Value.html) but we should probably define our own, because it would be visible in our public api and so on...on the other hand we could just take care that the detail field can be serialized to a string and then it is up to the consumer to handle it. Thoughts?

**Comment by petkovicdanilo** [comment]
I don't know which approach is the best to go with, but I could implement and submit pull request for whichever turns out to be the best.

**Comment by Furisto** [comment]
@petkovicdanilo Then I suggest we do the simple thing and ensure that the detail field is properly deserialized as a string. Do you want do it?

**Comment by petkovicdanilo** [comment]
Yeah, sure. I can try to do that.
